<h1><i class="fa fa-user"></i> Users</h1>

<a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'registration', 'action' => 'index')); ?>" class="btn btn-primary"><i class="fa fa-plus fa fa-white"></i> Add User</a>

<?php if ($this->users): ?>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($this->users as $user): ?>
            <tr>
                <td><?php echo $user->name; ?></td>
                <td><?php echo $user->email; ?></td>
                <td>
                    <div class="btn-group">
                        <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $user->userId)); ?>" class="btn btn-small">Edit</a>
                        <a href="" class="btn btn-small modalConfirm" data-modalmessage="Are you sure you want to delete this user?">Delete</a>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<?php
/*
echo $user->userId;
echo $user->password;
echo $this->date($user->dateCreated, Coda_View_Helper_Date::DATETIME);
echo $this->date($user->dateModified, Coda_View_Helper_Date::DATETIME);
echo $this->date($user->dateLoggedIn, Coda_View_Helper_Date::DATETIME);


*/
?>