<?php if($this->jobs):?>
<?php foreach ($this->jobs as $this->job):?>
<?php if ($this->job->jobStatusId!=4) continue; ?>
<p>
<?php if($this->job->carReg):?>   
The car registration is 
    <?php echo $this->job->carReg;?> 

<?php endif;?>
<br>

    <?php if($this->job->make):?>     
and the make is <?php echo $this->job->make;?>
<?php else:?>
<strong>(NO MAKE FOUND)</strong> <a href="<?php echo $this->url(array('module' => 'job', 'controller' => 'index', 'action' => 'edit', 'job' => $this->job->jobId)) ?>#make">click here to update</a>
    <?php endif;?>
<br>


the model is <?php echo $this->job->model;?>
<br>
The vehicle was booked in on <?php echo $this->job->insDate;?> this vehicle status is currently <?php echo $this->job->status->label;?>
</p>
<?php endforeach;?>
<?php endif;?>