<h1><i class="icon-th-list"></i> Zone99</h1>

<p>Zone99 items will be clips, fasteners, Wheel alignment ect.</p>

<p>Search form here. AJAX based, paginated.</p>

<a href="<?php echo $this->url(array('action' => 'add')); ?>" class="btn btn-primary"><i class="icon-plus icon-white"></i> Add Z99 Item</a>

<?php echo $this->partial('/partials/index-table.phtml', array('zone99s' => $this->zone99s))?>



