<h1><i class="icon-user"></i> Users</h1>

<a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'registration', 'action' => 'index')); ?>" class="btn btn-primary"><i class="icon-plus icon-white"></i> Add User</a>

<?php if ($this->users): ?>
    <table class="table">
        <thead>
            <tr>
                <th>userId</th>
                <th>name</th>
                <th>email</th>
                <th>password</th>
                <th>dateCreated</th>
                <th>dateModified</th>
                <th>dateLoggeddIn</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($this->users as $user): ?>
            <tr>
                <td><?php echo $user->userId; ?></td>
                <td><?php echo $user->name; ?></td>
                <td><?php echo $user->email; ?></td>
                <td><?php echo $user->password; ?></td>
                <td><?php echo $this->date($user->dateCreated, Coda_View_Helper_Date::DATETIME); ?></td>
                <td><?php echo $this->date($user->dateModified, Coda_View_Helper_Date::DATETIME); ?></td>
                <td><?php echo $this->date($user->dateLoggedIn, Coda_View_Helper_Date::DATETIME); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>