<h1><i class="icon-dashboard"></i> Dashboard</h1>

<?php
echo $this->partial('index/partials/table-data.phtml', array(
    'stage' => true,
    'jobStatus' => array(ECB_Model_JobStatus::WIP),
    'statuses' => $this->statuses,
    'processes' => $this->processes
));

echo $this->partial('index/partials/table-data.phtml', array(
    'stage' => false,
    'dateBookedIn' => true,
    'jobStatus' => array(ECB_Model_JobStatus::BOOKED_IN),
    'statuses' => $this->statuses
));

echo $this->partial('index/partials/table-data.phtml', array(
    'stage' => false,
    'jobStatus' => array(ECB_Model_JobStatus::TO_BOOK_IN),
    'statuses' => $this->statuses
));
?>
