<h1><i class="fa fa-dashboard"></i> Dashboard</h1>

<?php
echo $this->partial('index/partials/table-data.phtml', array(
    'stage' => true,
    'jobStatus' => array(ECB_Model_JobStatus::WIP),
    'statuses' => $this->statuses,
    'processes' => $this->processes
));

echo $this->partial('index/partials/table-data.phtml', array(
    'stage' => false,
    'dateBookedIn' => true,
    'jobStatus' => array(ECB_Model_JobStatus::BOOKED_IN),
    'statuses' => $this->statuses
));

echo $this->partial('index/partials/table-data.phtml', array(
    'stage' => false,
    'jobStatus' => array(ECB_Model_JobStatus::TO_BOOK_IN),
    'statuses' => $this->statuses
));
?>

<div id="modalNotes" class="modal hide fade" data-backdrop="false" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times"></i></button>
        <h3 id="myModalLabel">Notes</h3>
    </div>
    <div class="modal-body"></div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
</div>

<script>
    $('body').on('hidden', '#modalNotes', function () {
        $(this).removeData('modal');
    });
    $('.numberPlateTable').tooltip();
</script>