<h1><i class="icon-dashboard"></i> Dashboard</h1>

<div class="row-fluid">
    <div class="span12">
        <div class="box">
            <div class="box-header">
                <span class="title"><i class="icon-cogs"></i> W I P</span>
            </div>
            <div class="box-content padded">
                <?php echo $this->partial('index/partials/table-data.phtml', array(
                        'jobStatuses' => $this->wip,
                        'statuses' => $this->statuses,
                        'processes' => $this->processes,
                        'stage' => true
                    )); ?>
            </div>
        </div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        <div class="box">
            <div class="box-header">
                <span class="title">Booked In</span>
            </div>
            <div class="box-content padded">
                <?php echo $this->partial('index/partials/table-data.phtml', array(
                        'jobStatuses' => $this->bookedIn,
                        'statuses' => $this->statuses,
                        'processes' => $this->processes,
                        'stage' => false,
                        'dateBookedIn' => true
                    )); ?>
            </div>
        </div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        <div class="box">
            <div class="box-header">
                <span class="title">To be Booked In</span>
            </div>
            <div class="box-content padded">
                <?php echo $this->partial('index/partials/table-data.phtml', array(
                        'jobStatuses' => $this->toBeBookedIn,
                        'statuses' => $this->statuses,
                        'processes' => $this->processes,
                        'stage' => false
                    )); ?>
            </div>
        </div>
    </div>
</div>