<form class="form-horizontal" action="" method="post">
    
    <center><h1>Add Parts</h1></center>
    
    <div class="row-fluid">
    <div class="span1">
        <?php echo $this->form->quantity; ?>
    </div>
    <div class="row-fluid">
    <div class="span3">
        <?php echo $this->form->description; ?>
    </div>
        <div class="row-fluid">
    <div class="span2">
        <?php echo $this->form->cost; ?>
    </div>
            <div class="row-fluid">
    <div class="span2">
        <?php echo $this->form->discount; ?>
    </div>
         <div class="row-fluid">
    <div class="span2">
        <?php echo $this->form->vat; ?>
    </div>
          <div class="span2">
        <?php echo $this->form->total; ?>
    </div>

        <?php echo $this->form->save; ?>    
    
</form>