<table class="table">
   <thead>
       <tr>
           <th>Notes</th>
           <th>Customer</th>
           <th>Model</th>
           <th>ETA</th>
           <?php if ($this->auth()->isLoggedIn()): ?>
               <th>Action</th>
           <?php endif; ?>
       </tr>
   </thead>
   <tbody>
       <?php foreach ($this->data as $data): ?>
       <tr>
           <td>
               <?php // TODO: Note Count ?>
               0</td>
           <td>
               <span class="customer"><?php echo $data->name; ?></span>
               <span class="numberPlateTable"><?php echo $data->carReg; ?>
           </td>
           <td><?php echo $data->model; ?></td>
           <td>
               <?php // TODO: ETA ?>
               Days (INTEGER)</td>
           <?php if ($this->auth()->isLoggedIn()): ?>
               <td>
                    <div class="btn-group">
                        <a href="<?php echo $this->url(array('module' => 'job', 'controller' => 'index', 'action' => 'edit', 'job' => $data->jobId));?>" class="btn btn-mini"><i class="icon-edit"></i> Edit</a>
                        <button class="btn btn-mini dropdown-toggle" data-toggle="dropdown">
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li class="dropdown-submenu pull-left"><a>Stage</a>
                                <ul class="dropdown-menu">
                                    <?php foreach ($this->processes as $process): ?>
                                    <li><a href="<?php echo $this->url(array('module' => 'job', 'controller' => 'index', 'action' => 'set-process', 'job' => $data->jobId, 'process' => $process->jobProcessId));?>" class="modalConfirm" data-modalmessage="You are changing this to <?php echo $process->label; ?>"><?php echo $process->label; ?></a></li>
                                    <?php endforeach; ?>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </td>
            <?php endif; ?>
       </tr>
       <?php endforeach; ?>
   </tbody>
</table>