<h1><i class="icon-th-large"></i> Board</h1>

<form method="post" class="form-horizonal">
    <input type="text" name="search" placeholder="Search" />
    <input type="submit" value="Search ->Not yet working" class="btn btn-primary" />
</form>

<div class="row-fluid">
    <div class="span6">
        <div class="box">
            <div class="box-header">
                <span class="title">Strip</span>
            </div>
            <div class="box-content padded">
                <?php if ($this->strip->toArray()): ?>
                    <?php echo $this->partial('index/partials/board-table.phtml', array(
                            'data' => $this->strip,
                            'processes' => $this->processes
                    ))?>
               <?php endif; ?>
            </div>
        </div>
    </div>

    <div class="span6">
        <div class="box">
            <div class="box-header">
                <span class="title">Polish / Fit</span>
            </div>
            <div class="box-content padded">
                <?php if ($this->polishFit->toArray()): ?>
                    <?php echo $this->partial('index/partials/board-table.phtml', array(
                            'data' => $this->polishFit,
                            'processes' => $this->processes
                    ))?>
               <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<div class="row-fluid">
    <div class="span6">
        <div class="box">
            <div class="box-header">
                <span class="title">Paint</span>
            </div>
            <div class="box-content padded">
                <?php if ($this->paint->toArray()): ?>
                    <?php echo $this->partial('index/partials/board-table.phtml', array(
                            'data' => $this->paint,
                            'processes' => $this->processes
                    ))?>
               <?php endif; ?>
            </div>
        </div>
    </div>

    <div class="span6">
        <div class="box">
            <div class="box-header">
                <span class="title">Repair</span>
            </div>
            <div class="box-content padded">
                <?php if ($this->repair->toArray()): ?>
                    <?php echo $this->partial('index/partials/board-table.phtml', array(
                            'data' => $this->repair,
                            'processes' => $this->processes
                    ))?>
               <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<div class="row-fluid">
    <div class="span6">
        <div class="box">
            <div class="box-header">
                <span class="title">Prime</span>
            </div>
            <div class="box-content padded">
                <?php if ($this->prime->toArray()): ?>
                    <?php echo $this->partial('index/partials/board-table.phtml', array(
                            'data' => $this->prime,
                            'processes' => $this->processes
                    ))?>
               <?php endif; ?>
              </div>
        </div>
    </div>

    <div class="span6">
        <div class="box">
            <div class="box-header">
                <span class="title">Wash</span>
            </div>
            <div class="box-content padded">
                <?php if ($this->wash->toArray()): ?>
                    <?php echo $this->partial('index/partials/board-table.phtml', array(
                            'data' => $this->wash,
                            'processes' => $this->processes
                    ))?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>