<h1><i class="fa fa-th-large"></i> Board</h1>

<form method="post" class="form-horizonal">
    <input type="text" name="search" placeholder="Search" />
    <input type="submit" value="Search ->Not yet working" class="btn btn-primary" />
</form>

<div class="row-fluid">
    <div class="span6">
        <?php if ($this->strip->toArray()): ?>
            <?php echo $this->partial('index/partials/board-table.phtml', array(
                    'processes' => $this->processes,
                    'jobProcesses' => array(ECB_Model_JobProcess::STRIP)
            ))?>
       <?php endif; ?>
    </div>

    <div class="span6">
        <?php if ($this->polishFit->toArray()): ?>
            <?php echo $this->partial('index/partials/board-table.phtml', array(
                    'processes' => $this->processes,
                    'jobProcesses' => array(ECB_Model_JobProcess::POLISH_FIT)
            ))?>
       <?php endif; ?>
    </div>
</div>

<div class="row-fluid">
    <div class="span6">
        <?php if ($this->paint->toArray()): ?>
            <?php echo $this->partial('index/partials/board-table.phtml', array(
                    'processes' => $this->processes,
                    'jobProcesses' => array(ECB_Model_JobProcess::PAINT)
            ))?>
       <?php endif; ?>
    </div>

    <div class="span6">
        <?php if ($this->repair->toArray()): ?>
            <?php echo $this->partial('index/partials/board-table.phtml', array(
                    'processes' => $this->processes,
                    'jobProcesses' => array(ECB_Model_JobProcess::REPAIR)
            ))?>
       <?php endif; ?>
    </div>
</div>

<div class="row-fluid">
    <div class="span6">
        <?php if ($this->prime->toArray()): ?>
            <?php echo $this->partial('index/partials/board-table.phtml', array(
                    'processes' => $this->processes,
                    'jobProcesses' => array(ECB_Model_JobProcess::PRIME)
            ))?>
       <?php endif; ?>
    </div>

    <div class="span6">
        <?php if ($this->wash->toArray()): ?>
            <?php echo $this->partial('index/partials/board-table.phtml', array(
                    'processes' => $this->processes,
                    'jobProcesses' => array(ECB_Model_JobProcess::WASH)
            ))?>
        <?php endif; ?>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        <?php if ($this->prime->toArray()): ?>
            <?php echo $this->partial('index/partials/board-table.phtml', array(
                    'processes' => $this->processes,
                    'jobProcesses' => array(ECB_Model_JobProcess::COMPLETE)
            ))?>
       <?php endif; ?>
    </div>
</div>