<?php if ($this->zone99s): ?>
<table class="table">
    <thead>
        <tr>
            <th>Image</th>
            <th>Manufacturer</th>
            <th>Description</th>
            <th>Part Number</th>
            <th class="currency">Price</th>
        </tr>
    </thead>
    <tbody>
            <tr>
                <?php foreach($this->zone99s as $zone99): ?>
            <td><img src="<?php echo $zone99->image; ?>" width="60"></td>
            <td><?php echo $zone99->make; ?></td>
            <td><?php echo $zone99->description; ?></td>
            <td><?php echo $zone99->partNo; ?></td>
            <td class="currency"><?php echo $this->currency($zone99->price); ?></td>
            <td>
                <div class="btn-group">
                    <a href="<?php echo $this->url(array('action' => 'edit', 'z99Id' => $zone99->z99Id)); ?>" class="btn btn-mini"><i class="icon-edit"></i> Edit</a>
                    <a href="<?php echo $this->url(array('action' => 'delete', 'z99Id' => $zone99->z99Id)); ?>" class="btn btn-mini modalConfirm" data-modalmessage="Are you sure you want to delete this item"><i class="icon-remove"></i> Delete</a>
                </div>
            </td>
        </tr>

            <?php endforeach; ?>
        </tbody>
</table>
        <?php endif;?>





