<?php echo $this->headScript()->appendFile("/js/job/search.js") ?>

<h1><i class="fa fa-wrench"></i> Jobs</h1>

<form id="jobSearch" class="form-inline ajax">
    <input type="search" name="keyword" placeholder="Keyword" />
    <input type="submit" value="Search" />
    <a href="<?php echo $this->url(array('action' => 'add')); ?>" class="btn btn-primary pull-right"><i class="fa fa-plus fa fa-white"></i> Add Job</a>
</form>

<div id="resultContent">
    <?php echo $this->partial('partials/index-table.phtml', array(
            'jobs' => $this->jobs,
            'status' => $this->status,
            'statuses' => $this->statuses,
            'processes' => $this->processes
            )); ?>
</div>

<div id="modalNotes" class="modal hide fade" data-backdrop="false" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times"></i></button>
        <h3 id="myModalLabel">Notes</h3>
    </div>
    <div class="modal-body"></div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
</div>

<script>
    $('body').on('hidden', '#modalNotes', function () {
        $(this).removeData('modal');
    });
</script>