<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="fa fa-bar"></span>
                <span class="fa fa-bar"></span>
                <span class="fa fa-bar"></span>
            </a>

            <div class=" nav-collapse collapse">
                <ul class="nav nav-pills">
                    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'index'), 'default', true); ?>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'board', 'controller' => 'index', 'action' => 'index'), 'default', true); ?>"><i class="fa fa-th-large"></i> Board</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="fa fa-wrench"></i> Jobs <i class="fa fa-caret-down"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url(array('module' => 'job', 'controller' => 'index', 'action' => 'index'), 'default', true); ?>">All Jobs</a></li>
                            <li><a href="<?php echo $this->url(array('module' => 'job', 'controller' => 'index', 'action' => 'index', 'status' => '4'), 'default', true); ?>">WIP</a></li>
                            <li><a href="<?php echo $this->url(array('module' => 'job', 'controller' => 'index', 'action' => 'index', 'status' => '3'), 'default', true); ?>">Booked In</a></li>
                            <li><a href="<?php echo $this->url(array('module' => 'job', 'controller' => 'index', 'action' => 'index', 'status' => '2'), 'default', true); ?>">To Book In</a></li>
                            <li><a href="<?php echo $this->url(array('module' => 'job', 'controller' => 'index', 'action' => 'index', 'status' => '1'), 'default', true); ?>">Estimate</a></li>
                            <li><a href="<?php echo $this->url(array('module' => 'job', 'controller' => 'index', 'action' => 'index', 'status' => '5'), 'default', true); ?>">Complete</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="fa fa-gears"></i> Admin <i class="fa fa-caret-down"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url(array('module' => 'ccars', 'controller' => 'index', 'action' => 'index'), 'default', true); ?>"><i class="fa fa-truck"></i> Courtesy Cars</a></li>
                            <li><a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'index', 'action' => 'index'), 'default', true); ?>"><i class="fa fa-user"></i> Users</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="<?php echo $this->url(array('module' => 'todo', 'controller' => 'index', 'action' => 'index'), 'default', true); ?>"><i class="fa fa-tasks"></i> To Do</a>
                    </li>
                </ul>
            </div>

            <div class="pull-right">
                <ul class="nav">

                <?php if ($this->auth()->isLoggedIn()): ?>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-user"></i>
                            <?php echo $this->auth()->getUser()->name; ?>
                            <i class="fa fa-caret-down"></i>
                        </a>
                        <ul class="dropdown-menu">
                          <li>
                              <a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'auth', 'action' => 'change-password'), 'default', true); ?>"><i class="fa fa-key"></i> Change Password</a>
                          </li>
                        </ul>
                    </li>

                    <li><a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'auth', 'action' => 'logout'), 'default', true); ?>">Log out <i class="fa fa-sign-out"></i></a></li>
                <?php else: ?>
                    <li><a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'auth', 'action' => 'login'), 'default', true); ?>">Log in <i class="fa fa-sign-in"></i></a></li>
                <?php endif; ?>
                </ul>
            </div>
        </div>
    </div>
</div>
