<form class="form-inline" action="" method="post">

    <center><h1>Job Card</h1></center>

    <div class="row-fluid">
        <div class="span1">
            <?php echo $this->form->mechanical; ?>
        </div>
        <div class="span1">
            <?php echo $this->form->panel; ?>
        </div>
        <div class="span1">
            <?php echo $this->form->strip; ?>
        </div>
        <div class="span1">
            <?php echo $this->form->prep; ?>
        </div>
        <div class="span1">
            <?php echo $this->form->polish; ?>
        </div>
        <div class="span1">
            <?php echo $this->form->paint; ?>
        </div>
        <div class="span1">
            <?php echo $this->form->clean; ?>
        </div>
        <div class="span2">
            <?php echo $this->form->dateBooked; ?>
        </div>
        <div class="span1">
            <?php echo $this->form->jobId; ?>
            <?php echo $this->form->save; ?>
        </div>
    </div>
</form>

  