<?php if (! empty($this->card)): ?>
<table class="table">
    <thead>
        <tr>
            <th class="span1">Mechanical</th>
            <th class="span3">Panel</th>
            <th class="span2">Strip</th>
            <th class="span2">Prep</th>
            <th class="span1">Polish</th>
            <th class="span2">Fit</th>
            <th class="span2">Paint</th>
            <th class="span2">Clean</th>
            <th class="span2">Date Booked</th>
            
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->card as $jobCard): ?>
        <tr>
            <td><?php echo $jobCard->mechanical; ?></td>
            <td><?php echo $jobCard->panel; ?></td>
            <td><?php echo $jobCard->strip; ?></td>
            <td><?php echo $jobCard->prep; ?></td>
            <td><?php echo $jobCard->polish; ?></td>
            <td><?php echo $jobCard->fit; ?></td>
            <td><?php echo $jobCard->paint; ?></td>
            <td><?php echo $jobCard->clean; ?></td>
            <td><?php echo $jobCard->dateBooked; ?></td>
            
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php else: ?>
<p>No Hours</p>
<?php endif; ?>