<h1><i class="icon-dashboard"></i> Dashboard</h1>

<!--<p>Code pinched from '<a href="http://beer2code.com/themes/core-admin/pages/dashboard/dashboard.html" target="_blank">Core Admin</a>'</p>-->

<div class="row-fluid">
    <div class="span6">
        <div class="box">
            <div class="box-header">
                <span class="title">Dash Board Item 1</span>
            </div>
            <div class="box-content padded">
                I think a <i class="icon-calendar"></i> would look good here
            </div>
        </div>
    </div>

    <div class="span6">
        <div class="box">
            <div class="box-header">
                <span class="title"><i class='icon-plus'></i> Dash Board Item 2</span>
            </div>
            <div class="box-content padded">
               I think an <i class="icon-plus"></i> here to add to the <i class="icon-calendar-empty"></i> <?php// echo $this->partial('modules/diary/views/scripts/partials/diary_form.phtml', array('form' => $this->form))?>
            </div>
        </div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        <div class="box">
            <div class="box-header">
                <span class="title"><i class="icon-cogs"></i> W I P</span>
            </div>
            <div class="box-content padded">
               <table class="table">
                   <thead>
                       <tr>
                           <th>Car Reg</th>
                           <th>Customer</th>
                           <th>Make</th>
                           <th>Model</th>
                           <th>Stage</th>
                           <th>Action</th>
                       </tr>
                   </thead>
                   <tbody>
                       <?php foreach ($this->wip as $wip): ?>
                       <tr>
                           <td>
                               <span class="numberPlateTable"><?php echo $wip->carReg; ?></span>
                           </td>
                           <td><?php echo $wip->name; ?></td>
                           <td><?php echo $wip->make; ?></td>
                           <td><?php echo $wip->model; ?></td>
                           <td><?php echo $wip->process->label; ?></td>
                            <td>
                <div class="btn-group">
                    <a href="<?php echo $this->url(array('module' => 'job', 'controller' => 'index', 'action' => 'edit', 'job' => $wip->jobId));?>" class="btn btn-mini"><i class="icon-edit"></i> Edit</a>
                    <button class="btn btn-mini dropdown-toggle" data-toggle="dropdown">
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <li class="dropdown-submenu pull-left"><a>Status</a>
                            <ul class="dropdown-menu">
                                <?php foreach ($this->statuses as $status): ?>
                                <li><a href="<?php echo $this->url(array('module' => 'job', 'controller' => 'index', 'action' => 'set-status', 'job' => $wip->jobId, 'status' => $status->jobStatusId));?>" class="modalConfirm" data-modalmessage="You are changing this to <?php echo $status->label; ?>"><?php echo $status->label; ?></a></li>
                                <?php endforeach; ?>
                            </ul>
                        </li>
                        <li class="dropdown-submenu pull-left"><a>Stage</a>
                            <ul class="dropdown-menu">
                                <?php foreach ($this->processes as $process): ?>
                                <li><a href="<?php echo $this->url(array('module' => 'job', 'controller' => 'index', 'action' => 'set-process', 'job' => $wip->jobId, 'process' => $process->jobProcessId));?>" class="modalConfirm" data-modalmessage="You are changing this to <?php echo $process->label; ?>"><?php echo $process->label; ?></a></li>
                                <?php endforeach; ?>
                            </ul>
                        </li>
                    </ul>
                </div>
            </td>
                       </tr>
                       <?php endforeach; ?>
                   </tbody>
               </table>
            </div>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="span6">
        <div class="box">
            <div class="box-header">
                <span class="title">Ready to Invoice</span>
            </div>
            <div class="box-content padded">
               <table class="table">
                   <thead>
                       <tr>
                           <th>Car Reg</th>
                           <th>Customer</th>
                           <th>Make</th>
                           <th>Model</th>
                           <th>Action</th>

                       </tr>
                   </thead>
                   <tbody>
                       <?php foreach ($this->rdyToInvoice as $rdyToInvoice): ?>
                       <tr>
                           <td>
                               <span class="numberPlateTable"><?php echo $rdyToInvoice->carReg; ?></span>
                           </td>
                           <td><?php echo $rdyToInvoice->name; ?></td>
                           <td><?php echo $rdyToInvoice->make; ?></td>
                           <td><?php echo $rdyToInvoice->model; ?></td>
                            <td>
                <div class="btn-group">
                    <a href="<?php echo $this->url(array('module' => 'job', 'controller' => 'index', 'action' => 'edit', 'job' => $wip->jobId));?>" class="btn btn-mini"><i class="icon-edit"></i> Edit</a>
                            </ul>
                        </li>
                    </ul>
                </div>
            </td>
                       </tr>
                       <?php endforeach; ?>
                   </tbody>
               </table>
            </div>
        </div>
    </div>

    <div class="span6">
        <div class="box">
            <div class="box-header">
                <span class="title">Dash Board Item 5</span>
            </div>
            <div class="box-content padded">
               A list of Todays Calendar Entries listed here would look good
            </div>
        </div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        <div class="box">
            <div class="box-header">
                <span class="title">Booked In</span>
            </div>
            <div class="box-content padded">
                <table class="table">
                   <thead>
                       <tr>
                           <th>Car Reg</th>
                           <th>Customer</th>
                           <th>Postcode</th>
                           <th>Make</th>
                           <th>Model</th>
                            <th>Action</th>
                       </tr>
                   </thead>
                   <tbody>
                       <?php foreach ($this->bookedIn as $bookedIn): ?>
                       <tr>
                           <td><span class="numberPlateTable"><?php echo $bookedIn->carReg; ?></span></td>
                           <td><?php echo $bookedIn->name; ?></td>
                           <td><?php echo $bookedIn->postcode; ?></td>
                           <td><?php echo $bookedIn->make; ?></td>
                           <td><?php echo $bookedIn->model; ?></td>
                           <td>
                <div class="btn-group">
                    <a href="<?php echo $this->url(array('module' => 'job', 'controller' => 'index', 'action' => 'edit', 'job' => $wip->jobId));?>" class="btn btn-mini"><i class="icon-edit"></i> Edit</a>
                            </ul>
                        </li>
                    </ul>
                </div>
            </td>
                       </tr>
                       <?php endforeach; ?>
                   </tbody>
               </table>
            </div>
        </div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        <div class="box">
            <div class="box-header">
                <span class="title">To be Booked In</span>
            </div>
            <div class="box-content padded">
                <table class="table">
                   <thead>
                       <tr>
                           <th>Car Reg</th>
                           <th>Customer</th>
                           <th>Postcode</th>
                           <th>Make</th>
                           <th>Model</th>
                           <th>Action</th>
                       </tr>
                   </thead>
                   <tbody>
                       <?php foreach ($this->toBeBookedIn as $toBeBookedIn): ?>
                       <tr>
                           <td>
                               <span class="numberPlateTable"><?php echo $toBeBookedIn->carReg; ?></span>
                           </td>
                           <td><?php echo $toBeBookedIn->name; ?></td>
                           <td><?php echo $toBeBookedIn->postcode; ?></td>
                           <td><?php echo $toBeBookedIn->make; ?></td>
                           <td><?php echo $toBeBookedIn->model; ?></td>
                           <td>
                <div class="btn-group">
                    <a href="<?php echo $this->url(array('module' => 'job', 'controller' => 'index', 'action' => 'edit', 'job' => $wip->jobId));?>" class="btn btn-mini"><i class="icon-edit"></i> Edit</a>
                            </ul>
                        </li>
                    </ul>
                </div>
            </td>
                       </tr>
                       <?php endforeach; ?>
                   </tbody>
               </table>
            </div>
        </div>
    </div>
</div>