<h1><i class="icon-calendar"></i> Elite Carbody - Diary</h1>

<a href="<?php echo $this->url(array('action' => 'add')); ?>" class="btn btn-primary"><i class="icon-plus icon-white"></i> Add Diary Event</a>

<table class="table">
    <thead>
        <tr>
            <th>Subject</th>
            <th>Details</th>
            <th>Time</th>
            <th>Date Starting</th>
            <th>Date Ending</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->diarys as $diary): ?>
        <tr>
            <td><?php echo $diary->subject; ?></td>
            <td><?php echo $diary->details; ?></td>
            <td><?php echo $diary->time; ?></td>
            <td><?php echo $this->date($diary->dateBegin); ?></td>
            <td><?php echo $this->date($diary->dateEnd); ?></td>

            <td>
                <div class="btn-group">
                    <a href="<?php echo $this->url(array('action' => 'edit', 'diaryId' => $diary->diaryId)); ?>" class="btn btn-mini"><i class="icon-edit"></i> Edit</a>
                    <a href="<?php echo $this->url(array('action' => 'delete', 'diaryId' => $diary->diaryId)); ?>" class="btn btn-mini modalConfirm" data-modalmessage="Are you sure you want to delete this item"><i class="icon-remove"></i> Delete</a>
                </div>
            </td>
        </tr>
        <?php endforeach; ?>


