<form class="form-inline" action="" method="post">
    
    <center><h3>Diary Entry</h3></center>
    
    <div class="row-fluid">
    <div class="span2">
        <?php echo $this->form->subject; ?>
    </div>
    
    <div class="span4">
        <?php echo $this->form->details; ?>
    </div>
        
    <div class="span1">
        <?php echo $this->form->time; ?>
    </div>
            
    <div class="span1">
        <?php echo $this->form->dateBegin; ?>
    </div>
         
    <div class="span1">
        <?php echo $this->form->dateEnd; ?>
    </div>
          <div>
        <?php echo $this->form->diaryId; ?>
    </div>
    
    <div class="span1">
        <?php echo $this->form->save; ?>    
</div>
    </div>
    
</form>