<h1><i class="fa fa-truck"></i> Elite Car Body - Courtesy Cars</h1>

<a href="<?php echo $this->url(array('action' => 'add')); ?>" class="btn btn-primary"><i class="fa fa-plus fa fa-white"></i> Add Courtesy Car</a>

<table class="table">
    <thead>
        <tr>
            <th>Registration</th>
            <th>Description</th>
            <th>MOT date due</th>
            <th>Tax month due</th>
            <th>Service Due</th>
            <th>Booked on on</th>
            <th>Due back in</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->ccarsa as $ccars): ?>
        <tr>
            <td>
                <span class="numberPlateTable"><?php echo $ccars->reg; ?></span>
            </td>
            <td><?php echo $ccars->description; ?></td>
            <td><?php echo $this->date($ccars->motDue); ?></td>
            <td><?php echo $this->date($ccars->taxDue); ?></td>
            <td><?php echo $this->date($ccars->service); ?></td>
            <td><?php echo $this->date($ccars->bookedOut); ?></td>
            <td><?php echo $this->date($ccars->dueIn); ?></td>
            <td>
                <div class="btn-group">
                    <a href="<?php echo $this->url(array('action' => 'edit', 'carId' => $ccars->carId)); ?>" class="btn btn-mini"><i class="fa fa-edit"></i> Edit</a>
                    <a href="<?php echo $this->url(array('action' => 'delete', 'carId' => $ccars->carId)); ?>" class="btn btn-mini modalConfirm" data-modalmessage="Are you sure you want to delete this item"><i class="fa fa-remove"></i> Delete</a>
                </div>
            </td>
        </tr>
        <?php endforeach; ?>


