<form class="form-vertical" action="" method="post">

<center>
    <h2>Customer Details</h2>
</center>

<div class="row-fluid">
    <div class="span3">
        <h4>Customer Information</h4>
        <?php echo $this->form->insDate; ?>
        <?php echo $this->form->name; ?>
        <?php echo $this->form->address; ?>
        <?php echo $this->form->postcode; ?>
        <?php echo $this->form->tel; ?>
        <?php echo $this->form->mobile; ?>
        <?php echo $this->form->email; ?>
    </div>
    <div class="span3">
        <h4>Insurance Info</h4>
        <?php echo $this->form->insName; ?>
        <?php echo $this->form->insAdd; ?>
        <?php echo $this->form->insPost; ?>
        <?php echo $this->form->insTel; ?>
        <?php echo $this->form->excess; ?>
        <?php echo $this->form->vatRegistered; ?>
    </div>
    <div class="span3">
        <h4>Vehicle Information</h4>
        <?php echo $this->form->carReg; ?>
        <?php echo $this->form->make; ?>
        <?php echo $this->form->model; ?>
        <?php echo $this->form->mileage; ?>
        <?php echo $this->form->vin; ?>
        <?php echo $this->form->colour; ?>
        <?php echo $this->form->transmission; ?>
        <?php echo $this->form->fuel; ?>
    </div>
    <div class="span3">
        <h4>Internal Use</h4>
        <?php echo $this->form->jobStatusId; ?>
        <?php echo $this->form->jobProcessId; ?>
        <?php echo $this->form->seToyota; ?>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        <?php echo $this->form->damage; ?>
        <?php echo $this->form->special; ?>
        <?php echo $this->form->partsEst; ?>
    </div>
</div>

<h2>Estimate Details</h2>

<div class="row-fluid">
    <div class="span4">
        <?php echo $this->form->estPrep; ?>
        <?php echo $this->form->labRate; ?>
        <?php echo $this->form->labHours; ?>
    </div>
    <div class="span4">
        <?php echo $this->form->pandmEst; ?>
        <?php echo $this->form->partsTotal; ?>
        <?php echo $this->form->specialEst; ?>
        <?php echo $this->form->recovEst; ?>
    </div>
    <div class="span4">
        <?php echo $this->form->labEst; ?>
        <?php echo $this->form->subtotEst; ?>
        <?php echo $this->form->vatEst; ?>
        <?php echo $this->form->totalEst; ?>
    </div>
</div>

<?php echo $this->form->save; ?>

</form>