<h1><i class="icon-book"></i> Address Book</h1>

<p>This is an Address Book, where you can add addresses you use a lot of, SET, CLM ect, to then quickly insert into a new 'job'</p>

<a href="<?php echo $this->url(array('action' => 'add')); ?>" class="btn btn-primary"><i class="icon-plus icon-white"></i> Add Address</a>

<table class="table">
    <thead>
        <tr>
            <th>Description</th>
            <th>Name</th>
            <th>Address</th>
            <th>Postcode</th>
            <th>Home / office</th>
            <th>Mobile</th>
            <th>Email</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->addresses as $address): ?>
        <tr>
            <td><?php echo $address->description; ?></td>
            <td><?php echo $address->name; ?></td>
            <td><?php echo $address->address; ?></td>
            <td><?php echo $address->postcode; ?></td>
            <td><?php echo $address->homeTel; ?></td>
            <td><?php echo $address->mobileTel; ?></td>
            <td><?php echo $address->email; ?></td>
            <td>
                <div class="btn-group">
                    <a href="<?php echo $this->url(array('action' => 'edit', 'addressId' => $address->addressId)); ?>" class="btn btn-mini"><i class="icon-edit"></i> Edit</a>
                    <a href="<?php echo $this->url(array('action' => 'delete', 'addressId' => $address->addressId)); ?>" class="btn btn-mini modalConfirm" data-modalmessage="Are you sure you want to delete this address"><i class="icon-remove"></i> Delete</a>
                </div>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>