<h1><i class="icon-shopping-cart"></i> Purchases</h1>
<a href="<?php echo $this->url(array('action' => 'add')); ?>" class="btn btn-primary pull-right"><i class="icon-plus icon-white"></i> Add Purchase</a>

<?php if ($this->purchase): ?>
<table class="table">
    <thead>
        <tr>
            <th>Purchase Date</th>
            <th>Company</th>
            <th>Invoice Number</th>
            <th>Ref Number</th>
            <th>Total</th>
            <th>Due Date</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->purchase as $purchase): ?>
        <tr>
            <td><?php echo $this->date($purchase->purchaseDate); ?></td>
            <td><?php echo $purchase->company; ?></td>
            <td><?php echo $purchase->invoiceNumber; ?></td>
            <td><?php echo $purchase->referenceNumber; ?></td>
            <td><?php echo $this->currency($purchase->total); ?></td>
            <td><?php echo $this->date($purchase->dueDate); ?></td>
            <td><a href="<?php echo $this->url(array('action' => 'edit', 'id' => $purchase->id)); ?>" class="btn btn-mini"><i class="icon-edit"></i> Edit</a></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php else: ?>
<p>No purchases found</p>
<?php endif; ?>