            <div class="row-fluid">
                <div class="well">
                    <div class="span6">

                        <h4>Customer Info</h4>

                                <div class="control-group">
                                    <label class="control-label" for="carReg">Vehicle Reg</label>
                                    <div class="controls">
                                    <input name="carReg" type="carReg" id="carReg" class="numberPlate" value="<?php echo $job->carReg; ?>" />
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="insDate">Inspection Date</label>
                                    <div class="controls">
                                        <input type="date" id="insDate" name="insDate" value="<?php echo $job->insDate; ?>" />
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="name">Customer Name</label>
                                    <div class="controls">
                                        <input type="text" id="name" name="name" value="<?php echo $job->name; ?>" />
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="address">Customer Address</label>
                                    <div class="controls">
                                        <textarea id="address" name="address"><?php echo $job->address; ?></textarea>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="postcode">Customer Postcode</label>
                                    <div class="controls">
                                        <input type="text" id="postcode" name="postcode" value="<?php echo $job->postcode; ?>" />
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="tel">Home Tel</label>
                                    <div class="controls">
                                        <input type="tel" id="home" name="tel" value="<?php echo $job->home; ?>" />
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="mobile">Mobile Tel</label>
                                    <div class="controls">
                                        <input type="tel" id="mob" name="mobile" value="<?php echo $job->mob; ?>" />
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="email">Email Address</label>
                                    <div class="controls">
                                        <input type="email" id="email" name="email" value="<?php echo $job->email; ?>" />
                                    </div>
                                </div>
                    </div>

                    <div class="span6">
                        <h4>Insurance Info</h4>

                                <div class="control-group">
                                    <label class="control-label" for="insName">Insurance Company Name</label>
                                    <div class="controls">
                                        <input type="text" id="insName" name="insName" value="<?php echo $job->insName; ?>" />
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="insAdd">Insurance Company Address</label>
                                    <div class="controls">
                                        <textarea id="insAdd" name="insAdd"><?php echo $job->insAdd; ?></textarea>
                                    </div>
                                    </div>

                                <div class="control-group">
                                    <label class="control-label" for="insPost">Insurance Company Postcode</label>
                                    <div class="controls">
                                        <input type="text" id="insPost" name="insPost" value="<?php echo $job->insPost; ?>" />
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="insTel">Insurance Company Tel</label>
                                    <div class="controls">
                                        <input type="tel" id="insTel" name="insTel" value="<?php echo $job->insTel; ?>" />
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="excess">Excess Amount</label>
                                    <div class="controls">
                                        <input type="number" id="excess" name="excess" value="<?php echo $job->excess; ?>" />
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="vatRegistered">Vat Registered?</label>
                                    <div class="controls">
                                        <select id="vatReg" name="vatReg">
                                            <option>Select</option>
                                            <option value="1" <?php echo isSelected($job->vatReg, 1); ?>>Yes</option>
                                            <option value="0" <?php echo isSelected($job->vatReg, 0); ?>>No</option>
                                        </select>
                                    </div>
                                </div>

                    </div>

                        <div class="span12" style="margin-left:0px;">

                                <div class="control-group">
                                    <label class="control-label" for="damage">Bodywork Description</label>
                                    <div class="controls">
                                        <textarea id="damage" name="damage" class="span12"><?php echo $job->damage; ?></textarea>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="special">Specialist / Sub-Contracted work</label>
                                    <div class="controls">
                                        <textarea id="special" name="special" class="span12"><?php echo $job->special; ?></textarea>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="partsEst">Parts required</label>
                                    <div class="controls">
                                        <textarea id="partsEst" name="partsEst" class="span12"><?php echo $job->partsEst; ?></textarea>
                                    </div>
                                </div>
                        </div>

                    <div class="clearfix"></div>
                </div>




                </div>
             <!-- End Row -->

            <div class="row-fluid" id="form">


                <div class="span6">
                    <div class="well">

                        <h4>Vehicle Info</h4>

                                <div class="control-group">
                                    <label class="control-label" for="make">Vehicle Make</label>
                                    <div class="controls">
                                        <input type="text" id="make" name="make" value="<?php echo $job->make; ?>" />
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="model">Vehicle Model</label>
                                    <div class="controls">
                                        <input type="text" id="model" name="model" value="<?php echo $job->model; ?>" />
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="mileage">Mileage</label>
                                    <div class="controls">
                                        <input type="number" id="mileage" name="mileage" value="<?php echo $job->mileage; ?>" />
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="vin">Vin/Chassis Number</label>
                                    <div class="controls">
                                        <input type="text" id="vin" name="vin" value="<?php echo $job->vin; ?>" />
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="inputEmail">Tranmission</label>
                                    <div class="controls">
                                        <label class="radio">
                                            <input type="radio" name="transmission" id="transmission" value="Manual" <?php echo isChecked($job->transmission, "Manual"); ?> />
                                            Manual
                                        </label>
                                        <label class="radio">
                                            <input type="radio" name="transmission" id="transmission" value="Auto" <?php echo isChecked($job->transmission, "Auto"); ?> />
                                            Automatic
                                        </label>
                                        <label class="radio">
                                            <input type="radio" name="transmission" id="transmission" value="Unknown" <?php echo isChecked($job->transmission, "Unknown"); ?> />
                                            Unknown
                                        </label>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="colour">Colour</label>
                                    <div class="controls">
                                        <input type="text" id="colour" name="colour" value="<?php echo $job->colour; ?>" />
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="fuel">Fuel Type</label>
                                    <div class="controls">
                                        <label class="radio">
                                            <input type="radio" name="fuel" id="fuel" value="Petrol" <?php echo isChecked($job->fuel, "Petrol"); ?> />
                                            Petrol
                                        </label>
                                        <label class="radio">
                                            <input type="radio" name="fuel" id="fuel" value="Diesel" <?php echo isChecked($job->fuel, "Diesel"); ?> />
                                            Diesel
                                        </label>
                                        <label class="radio">
                                            <input type="radio" name="fuel" id="fuel" value="Hybrid" <?php echo isChecked($job->fuel, "Hybrid"); ?> />
                                            Hybrid
                                        </label>
                                        <label class="radio">
                                            <input type="radio" name="fuel" id="fuel" value="Electric" <?php echo isChecked($job->fuel, "Electric"); ?> />
                                            Electric
                                        </label>
                                        <label class="radio">
                                            <input type="radio" name="fuel" id="fuel" value="LPG" <?php echo isChecked($job->fuel, "LPG"); ?> />
                                            LPG
                                        </label>
                                        <label class="radio">
                                            <input type="radio" name="fuel" id="fuel" value="Unknown" <?php echo isChecked($job->fuel, "Unknown"); ?> />
                                            Unknown
                                        </label>
                                    </div>
                                </div>
                    </div>
                </div>

                <div class="span6">

                    <div class="well">
                        <h4>Internal Use</h4>

                                <div class="control-group">
                                    <label class="control-label" for="jobStatusId">Status</label>
                                    <div class="controls">
                                        <select id="jobStatusId" name="jobStatusId">
                                            <?php
                                                $s = "SELECT * FROM jobStatus";
                                                $sRes = mysql_query($s) or die (mysql_error());
                                                while ($jobStatus = mysql_fetch_object($sRes)):
                                            ?>
                                            <option value="<?php echo $jobStatus->label; ?>" <?php echo isSelected($job->jobStatusId, $jobStatus->label)?>><?php echo $jobStatusId->label; ?></option>
                                            <?php endwhile; ?>
                                        </select>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="inputEmail">Stage of Process</label>
                                    <div class="controls">

                                        <select id="jobProcessId" name="jobProcess">
                                            <option value="">Select from below</option>
                                            <?php
                                                $s = "SELECT * FROM jobProcess";
                                                $sRes = mysql_query($s) or die (mysql_error());
                                                while ($jobProcess = mysql_fetch_object($sRes)):
                                            ?>
                                            <option value="<?php echo $jobProcess->label; ?>" <?php echo isSelected($jobProcess->jobProcessId, $jobProcess->label)?>><?php echo $jobProcessId->label; ?></option>
                                            <?php endwhile; ?>
                                        </select>


                                    </div>
                                </div>

                                <div class="btn-group">
                                    <label class="control-label" for="seToyota"></label>
                                    <div class="controls">
                                        <label class="checkbox">
                                            <input type="hidden" name="seToyota" value="0" />
                                            <input type="checkbox" id="seToyota" name="seToyota" value="1" <?php echo isChecked($jobt->seToyota, 1)?> />
                                            SE Toyota Vehicle
                                        </label>
                                    </div>
                                </div>

                    </div> <!-- End Well -->

                    <div class="well">

                      
                                <div class="control-group">
                                    <label class="control-label" for="estPrep">Estimate Prepared by:</label>
                                    <div class="controls">
                                        <input type="text" id="estPrep" name="estPrep" value="<?php echo $job->estPrep; ?>" />
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="labRate">Labour Rate</label>
                                    <div class="controls">
                                        <div class="input-prepend">
                                            <span class="add-on"><i class="icon-gbp"></i></span>
                                            <input type="number" id="labRate" name="labRate" value="<?php echo $job->labRate; ?>">

                                        </div>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="labHours">Total Hours</label>
                                    <div class="controls">
                                        <div class="input-prepend">
                                            <span class="add-on">Hr</span>
                                            <input type="number" id="labHours" name="labHours" value="<?php echo $job->labHours; ?>">
                                        </div>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="labEst">Total Labour</label>
                                    <div class="controls">
                                        <div class="input-prepend">
                                            <span class="add-on"><i class="icon-gbp"></i></span>
                                            <input type="number" id="labEst" name="labEst" readonly="readonly" value="<?php echo $job->labEst; ?>" />
                                        </div>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="pandmEst">Paint & Materials</label>
                                    <div class="controls">
                                        <div class="input-prepend">
                                            <span class="add-on"><i class="icon-gbp"></i></span>
                                            <input type="number" id="pandmEst" name="pandmEst" value="<?php echo $job->pandmEst; ?>">
                                        </div>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="partsTotal">Total Parts</label>
                                    <div class="controls">
                                        <div class="input-prepend">
                                            <span class="add-on"><i class="icon-gbp"></i></span>
                                            <input type="number" id="partsTotal" name="partsTotal" value="<?php echo $job->partsTotal; ?>">
                                        </div>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="specialEst">Specialists Costs</label>
                                    <div class="controls">
                                        <div class="input-prepend">
                                            <span class="add-on"><i class="icon-gbp"></i></span>
                                            <input type="number" id="specialEst" name="specialEst" value="<?php echo $job->specialEst; ?>">
                                        </div>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="recovEst">Recovery Charge</label>
                                    <div class="controls">
                                        <div class="input-prepend">
                                            <span class="add-on"><i class="icon-gbp"></i></span>
                                            <input type="number" id="recovEst" name="recovEst" value="<?php echo $job->recovEst; ?>">
                                        </div>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="subtotEst">Sub-Total</label>
                                    <div class="controls">
                                        <div class="input-prepend">
                                            <span class="add-on"><i class="icon-gbp"></i></span>
                                            <input type="number" id="subtotEst" name="subtotEst" readonly="readonly" value="<?php echo $job->subtotEst; ?>" />
                                        </div>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="vatEst">VAT amount</label>
                                    <div class="controls">
                                        <div class="input-prepend">
                                            <span class="add-on"><i class="icon-gbp"></i></span>
                                            <input type="number" id="vatEst" name="vatEst" readonly="readonly" value="<?php echo $job->vatEst; ?>" />
                                        </div>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="totalEst">Total Estimate Cost</label>
                                    <div class="controls">
                                        <div class="input-prepend">
                                            <span class="add-on"><i class="icon-gbp"></i></span>
                                            <input type="number" id="totalEst" name="totalEst" readonly="readonly" value="<?php echo $job->totalEst; ?>" />
                                        </div>
                                    </div>
                                      </div>
                         </div>
            </div>
            </div>
        
    
            



<script type="text/javascript">
    $(document).ready(function() {
        $(document).on('keyup', $('#labRate'), function(){
            $('#labEst').val( parseFloat( $('#labRate').val() * $('#labHours').val() ).toFixed(2) )

            $('#subtotEst').val(
                parseFloat(
                    parseFloat($('#labEst').val()) +
                    parseFloat($('#pandmEst').val()) +
                    parseFloat($('#partsTotal').val()) +
                    parseFloat($('#recovEst').val()) +
                    parseFloat($('#specialEst').val())
                ).toFixed(2)
            )

            $('#vatEst').val( parseFloat( parseFloat($('#subtotEst').val()) * 0.2 ).toFixed(2) )

            $('#totalEst').val( parseFloat( parseFloat($('#subtotEst').val()) + parseFloat($('#vatEst').val()) ).toFixed(2) )
        });
    })
</script>
