<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('E C B');
echo $this->doctype(); ?>
<head>
    <?php echo $this->headMeta(); ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css')
                                 //->appendStylesheet($this->baseUrl().'/css/bootstrap-responsive.css')
                                 ->appendStylesheet($this->baseUrl().'//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css')
                                 ->appendStylesheet('//code.jquery.com/ui/1.10.3/themes/ui-darkness/jquery-ui.css')
                                 ->appendStylesheet($this->baseUrl().'/css/site.css'); ?>
    <?php echo $this->headScript()->prependFile("//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js")
                                   ->appendFile("//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js")
                                   ->appendFile('//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js')
                                   ->appendFile($this->baseUrl().'/js/site.js'); ?>
<script src=""></script>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <style type="text/css">
      .container > footer p {
        text-align: center; /* center align it with the container */
      }
      .container {
        width: 1020px; /* downsize our container to make the content feel a bit tighter and more cohesive. NOTE: this removes two full columns from the grid, meaning you only go to 14 columns and not 16. */
      }

      .container-fluid {
        max-width: 1020px;
        margin: 40px auto;
      }

      /* The white background content wrapper */
      .content {
        background-color: #fff;
        padding: 20px;
        /*margin: 0 -20px 50px; *//* negative indent the amount of the padding to maintain the grid system */
        -webkit-border-radius: 0 0 6px 6px;
           -moz-border-radius: 0 0 6px 6px;
                border-radius: 0 0 6px 6px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.15);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.15);
                box-shadow: 0 1px 2px rgba(0,0,0,.15);
      }

      /* Page header tweaks */
      .page-header {
        background-color: #f5f5f5;
        padding: 20px 20px 10px;
        margin: -20px -20px 20px;
      }
        </style>
</head>
<body>

<?php echo $this->partial('partials/navigation.phtml', array('sitesearch' => $this->sitesearch)); ?>

<div id="content">
    <div class="container-fluid">
        <div class="content">

            <?php echo $this->flash() ?>

            <?php echo $this->layout()->content; ?>

        </div>
<!--
      <footer>
      Footer Content here.
      </footer>
 -->
    </div> <!-- /container -->
</div>
</body>
</html>