<?php echo $this->headScript()->appendFile("/js/job/search.js") ?>

<h1><i class="icon-wrench"></i> Jobs</h1>

<form id="jobSearch" class="form-inline ajax">
    <input type="search" name="keyword" placeholder="Keyword" />
    <input type="submit" value="Search" />
    <a href="<?php echo $this->url(array('action' => 'add')); ?>" class="btn btn-primary pull-right"><i class="icon-plus icon-white"></i> Add Job</a>
</form>

<div id="resultContent">
    <?php echo $this->partial('partials/index-table.phtml', array('jobs' => $this->jobs, 'statuses' => $this->statuses, 'processes' => $this->processes)); ?>
</div>

