<h1>Zone99 :)</h1>

<p>Zone99 items will be clips, fasteners, Wheel alignment ect.</p>
<p>Needs edit & delete function COMPLETE?</p>

<?php echo $this->form; ?>
<?php echo $this->zone99Form; ?>
<table class="table">
    <thead>
        <tr>
            <th>Image</th>
            <th>Manufacturer</th>
            <th>Description</th>
            <th>Part Number</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->zone99s as $zone99): ?>
        <tr>
            <td><img src="<?php echo $zone99->image; ?>"></td>
            <td><?php echo $zone99->make; ?></td>
            <td><?php echo $zone99->description; ?></td>
            <td><?php echo $zone99->partNo; ?></td>
            <td><?php echo $zone99->price; ?></td>
            <td>
                <div class="btn-group">
                    <a href="<?php echo $this->url(array('action' => 'delete', 'z99Id' => $zone99->z99Id)); ?>" class="btn btn-mini modalConfirm" data-modalmessage="Are you sure you want to delete this item">Delete</a>
                    <a href="<?php echo $this->url(array('action' => 'edit', 'z99Id' => $zone99->z99Id)); ?>" class="btn btn-mini">Edit</a>
                </div>
            </td>
        </tr>
        <?php endforeach; ?>


