<table class="table">
    <thead>
        <tr>
            <th>Car Reg</th>
            <th>Customer</th>
            <?php if ($this->postcode): ?>
            <th>Postcode</th>
            <?php endif; ?>
            <th>Make</th>
            <th>Model</th>
            <?php if ($this->stage):?>
            <th>Stage</th>
            <?php endif; ?>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->jobStatuses as $jobStatus): ?>
        <tr>
            <td>
                <span class="numberPlateTable"><?php echo $jobStatus->carReg; ?></span>
            </td>
            <td><?php echo $jobStatus->name; ?></td>
            <?php if ($this->postcode): ?>
            <td><?php echo $jobStatus->postcode; ?></td>
            <?php endif; ?>
            <td><?php echo $jobStatus->make; ?></td>
            <td><?php echo $jobStatus->model; ?></td>
            <?php if ($this->stage): ?>
            <td><?php echo $jobStatus->process->label; ?></td>
            <?php endif; ?>
            <td>
                <div class="btn-group">
                    <a href="<?php echo $this->url(array('module' => 'job', 'controller' => 'index', 'action' => 'edit', 'job' => $jobStatus->jobId));?>" class="btn btn-mini"><i class="icon-edit"></i> Edit</a>
                    <button class="btn btn-mini dropdown-toggle" data-toggle="dropdown">
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <li class="dropdown-submenu pull-left"><a>Status</a>
                            <ul class="dropdown-menu">
                                <?php foreach ($this->statuses as $status): ?>
                                <li><a href="<?php echo $this->url(array('module' => 'job', 'controller' => 'index', 'action' => 'set-status', 'job' => $jobStatus->jobId, 'status' => $status->jobStatusId));?>" class="modalConfirm" data-modalmessage="You are changing this to <?php echo $status->label; ?>"><?php echo $status->label; ?></a></li>
                                <?php endforeach; ?>
                            </ul>
                        </li>
                        <?php if ($this->stage): ?>
                        <li class="dropdown-submenu pull-left"><a>Stage</a>
                            <ul class="dropdown-menu">
                                <?php foreach ($this->processes as $process): ?>
                                <li><a href="<?php echo $this->url(array('module' => 'job', 'controller' => 'index', 'action' => 'set-process', 'job' => $jobStatus->jobId, 'process' => $process->jobProcessId));?>" class="modalConfirm" data-modalmessage="You are changing this to <?php echo $process->label; ?>"><?php echo $process->label; ?></a></li>
                                <?php endforeach; ?>
                            </ul>
                        </li>
                        <?php endif; ?>
                    </ul>
                </div>
            </td>
        </tr>
        <?php endforeach; ?>
   </tbody>
</table>