<?php
    $this->headScript()->appendFile("/js/job/job.js")
                       ->appendFile("/js/job/part.js")
                       ->appendFile("/js/job/note.js")
?>

<h1><i class="icon-wrench"></i> Edit Job</h1>
<center>
    <p><span class="numberPlateTable"><?php echo $this->job->carReg; ?></span></p>
</center>

<div class='box'>
    <div class='box-header'>
<ul class="nav nav-tabs">
  <li class="active"><a href="#job" data-toggle="tab"><i class="icon-wrench"></i> Job</a></li>
  <li><a href="#jobPart" data-toggle="tab"><i class="icon-shopping-cart"> Parts</i></a></li>
  <li><a href="#jobNote" data-toggle="tab"><i class="icon-comments"></i> Notes</a></li>
  <li><a href="#jobImage" data-toggle="tab"><i class="icon-picture"> Images</i></a></li>
  <li><a href="#jobCard" data-toggle="tab"><i class="icon-time"></i> Job Card</a></li>
</ul>
    </div>
</div>
<div class="tab-content">
    <div class="tab-pane active" id="job">
        <?php echo $this->partial('partials/job.phtml', array('form' => $this->jobForm))?>
        <?php //echo $this->jobForm; ?>
    </div>
    <div class="tab-pane" id="jobPart">
        <?php //echo $this->jobPartForm; ?>
        <?php echo $this->partial('partials/addPart_form.phtml', array('form' => $this->jobPartForm)) ?>
        <div class="resultContent">
            <?php echo $this->partial('partials/job-part.phtml', array('job' => $this->job, 'parts' => $this->job->parts));?>
        </div>
    </div>
    <div class="tab-pane" id="jobNote">
        <div class="row-fluid">
            <?php echo $this->jobNoteForm; ?>
        </div>
        <div class="resultContent">
            <?php echo $this->partial('partials/job-note.phtml', array('notes' => $this->job->notes));?>
        </div>
    </div>
    <div class="tab-pane" id="jobImage">
        <p>Job Image</p>
    </div>
    <div class="tab-pane" id="jobCard">
        <p>Job Card</p>
       <?php echo $this->partial('partials/addJobCard_form.phtml', array('form' => $this->jobCardForm)) ?>
       <?php echo $this->partial('partials/job-card.phtml', array('job' => $this->job, 'card' => $this->job->card));?>

        <pre>
        <?php ($this->job->card->toArray()); ?>
        </pre>

    </div>
</div>
