<h1><i class="icon-dashboard"></i> Dashboard</h1>

<!--<p>Code pinched from '<a href="http://beer2code.com/themes/core-admin/pages/dashboard/dashboard.html" target="_blank">Core Admin</a>'</p>-->

<div class="row-fluid">
    <div class="span6">
        <div class="box">
            <div class="box-header">
                <span class="title">Dash Board Item 1</span>
            </div>
            <div class="box-content padded">
                I think a <i class="icon-calendar"></i> would look good here
            </div>
        </div>
    </div>

    <div class="span6">
        <div class="box">
            <div class="box-header">
                <span class="title"><i class='icon-plus'></i> Dash Board Item 2</span>
            </div>
            <div class="box-content padded">
               I think an <i class="icon-plus"></i> here to add to the <i class="icon-calendar-empty"></i> <?php// echo $this->partial('modules/diary/views/scripts/partials/diary_form.phtml', array('form' => $this->form))?>
            </div>
        </div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        <div class="box">
            <div class="box-header">
                <span class="title"><i class="icon-cogs"></i> W I P</span>
            </div>
            <div class="box-content padded">
                <?php echo $this->partial('index/partials/table-data.phtml', array('jobStatuses' => $this->wip, 'statuses' => $this->statuses, 'processes' => $this->processes, 'stage' => true, 'postcode' => true ))?>
            </div>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="span6">
        <div class="box">
            <div class="box-header">
                <span class="title">Ready to Invoice</span>
            </div>
            <div class="box-content padded">
                <?php echo $this->partial('index/partials/table-data.phtml', array('jobStatuses' => $this->rdyToInvoice, 'statuses' => $this->statuses, 'processes' => $this->processes, 'stage' => false, 'postcode' => false ))?>
            </div>
        </div>
    </div>

    <div class="span6">
        <div class="box">
            <div class="box-header">
                <span class="title">Dash Board Item 5</span>
            </div>
            <div class="box-content padded">
               A list of Todays Calendar Entries listed here would look good
            </div>
        </div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        <div class="box">
            <div class="box-header">
                <span class="title">Booked In</span>
            </div>
            <div class="box-content padded">
                <?php echo $this->partial('index/partials/table-data.phtml', array('jobStatuses' => $this->bookedIn, 'statuses' => $this->statuses, 'processes' => $this->processes, 'stage' => false, 'postcode' => true ))?>
            </div>
        </div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        <div class="box">
            <div class="box-header">
                <span class="title">To be Booked In</span>
            </div>
            <div class="box-content padded">
                <?php echo $this->partial('index/partials/table-data.phtml', array('jobStatuses' => $this->toBeBookedIn, 'statuses' => $this->statuses, 'processes' => $this->processes, 'stage' => false, 'postcode' => true ))?>
            </div>
        </div>
    </div>
</div>