<h2 class="center">Job Card</h1>

<form class="form-vertical" action="" method="post">
    <div class="row-fluid">
        <div class="span1">
            <?php echo $this->form->mechanical; ?>
        </div>
        <div class="span1">
            <?php echo $this->form->panel; ?>
        </div>
        <div class="span1">
            <?php echo $this->form->strip; ?>
        </div>
        <div class="span1">
            <?php echo $this->form->prep; ?>
        </div>
        <div class="span1">
            <?php echo $this->form->polish; ?>
        </div>
        <div class="span1">
            <?php echo $this->form->paint; ?>
        </div>
        <div class="span1">
            <?php echo $this->form->clean; ?>
        </div>
        <div class="span2">
            <?php echo $this->form->dateBooked; ?>
        </div>

    </div>
    <?php //echo $this->form->save; ?>
    <button name="save" id="save" type="submit" class="btn btn-success"><nobr>Save <i class="icon-ok"></i></nobr></button>
    <?php echo $this->form->jobId; ?>
</form>