<?php if ($this->jobs): ?>
<table class="indexTable table padded table-condensed">
    <thead>
        <tr>
            <th><i class="fa fa-file-text-o"></i></th>
            <th>Customer</th>
            <?php if ($this->status == 4): ?>
            <th>Co-Ord</th>
            <?php endif; ?>
            <th>Site</th>
            <th>Model</th>
            <?php if (in_array($this->status, array(2,3,4))): ?>
            <th>Loan Car</th>
            <th>Job Source</th>
            <?php endif; ?>
            <?php if ($this->status == 4): ?>
            <th>Stage</th>
            <th>ETA</th>
            <th>Lead Time</th>
            <?php endif; ?>
            <?php if ($this->status == 3): ?>
            <th>Booked In Date</th>
            <?php endif;?>
            <th>Status</th>
            <th>Created</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->jobs as $job): ?>
        <tr class="<?php echo strtolower($job->jobSource); ?>">
            <td><a href="<?php echo $this->url(array('module' => 'job', 'controller' => 'index', 'action' => 'add-note', 'jobId' => $job->jobId)); ?>" data-toggle="modal" data-target="#modalNotes"><?php echo count($job->notes); ?></a></td>
            <td>
                <span class="numberPlateTable"><?php echo $job->carReg; ?></span>
                <span class="customer"><?php echo $job->name; ?></span>
            </td>
            <?php if ($this->status == 4): ?>
            <td><?php echo $job->coordinator; ?></td>
            <?php endif; ?>
            <td><span class="label site <?php echo strtolower(str_replace(".", "", str_replace(" ", "", $job->site))); ?>"><?php echo $job->site ?></span></td>
            <td><?php echo $job->model; ?></td>
            <?php if (in_array($this->status, array(2,3,4))): ?>
            <td>LOAN CAR</td>
            <td><?php echo $job->jobSource; ?></td>
            <?php endif;?>
            <?php if ($this->status == 4): ?>
            <td><?php echo $job->process->label; ?></td>
            <td><span title="<?php echo $this->date($job->onSite, Coda_View_Helper_Date::DATE); ?>"><?php echo $this->date($job->eta, Coda_View_Helper_Date::ETA); ?></span></td>
            <td><?php echo ($this->date($job->onSite, Coda_View_Helper_Date::ETA) * -1); ?></td>
            <?php endif; ?>
            <?php if ($this->status == 3): ?>
            <td>Booked In Date</td>
            <?php endif;?>
            <td>
                <span class="label <?php echo strtolower($job->status->class); ?>"><?php echo $job->status->label; ?></span>
            </td>
            <td><?php echo $this->date($job->dateCreated, Coda_View_Helper_Date::DATE); ?></td>

            <td>
                <div class="btn-group">
                    <a href="<?php echo $this->url(array('action' => 'edit', 'job' => $job->jobId));?>" class="btn btn-mini"><i class="fa fa-edit"></i> Edit</a>
                    <button class="btn btn-mini dropdown-toggle" data-toggle="dropdown">
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <li class="dropdown-submenu pull-left"><a>Status</a>
                            <ul class="dropdown-menu">
                                <?php foreach ($this->statuses as $status): ?>
                                <li><a href="<?php echo $this->url(array('action' => 'set-status', 'job' => $job->jobId, 'status' => $status->jobStatusId));?>" class="modalConfirm" data-modalmessage="You are changing this to <?php echo $status->label; ?>"><?php echo $status->label; ?></a></li>
                                <?php endforeach; ?>
                            </ul>
                        </li>
                        <?php if ($job->jobStatusId == ECB_Model_JobStatus::WIP): ?>
                        <li class="dropdown-submenu pull-left"><a>Stage</a>
                            <ul class="dropdown-menu">
                                <?php foreach ($this->processes as $process): ?>
                                <li><a href="<?php echo $this->url(array('action' => 'set-process', 'job' => $job->jobId, 'process' => $process->jobProcessId));?>" class="modalConfirm" data-modalmessage="You are changing this to <?php echo $process->label; ?>"><?php echo $process->label; ?></a></li>
                                <?php endforeach; ?>
                            </ul>
                        </li>
                        <?php endif; ?>
                    </ul>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<?php endif;?>