<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>

            <div class=" nav-collapse collapse">
                <ul class="nav nav-pills">
                    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'index')); ?>"><i class="icon-dashboard"></i> Dashboard</a></li>
                    <li><a href="<?php echo $this->url (array('module' => 'board', 'controller' => 'index', 'action' => 'index')); ?>"><i class="icon-list-alt"></i> Board</a></li>
                    <li><a href="<?php echo $this->url (array('module' => 'report', 'controller' => 'index', 'action' => 'index')); ?>"><i class="icon-bar-chart"></i> Report</a></li>
                     <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="icon-wrench"></i> Jobs <i class="icon-caret-down"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url(array('module' => 'job', 'controller' => 'index', 'action' => 'index')); ?>"><i class="icon-wrench"></i> Jobs</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="icon-gears"></i> Admin <i class="icon-caret-down"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url(array('module' => 'address', 'controller' => 'index', 'action' => 'index'), 'default', true); ?>"><i class="icon-book"></i> Address Book</a></li>
                            <li><a href="<?php echo $this->url(array('module' => 'zone99', 'controller' => 'index', 'action' => 'index'), 'default', true); ?>"><i class="icon-th-list"></i> Zone99</a></li>
                            <li><a href="<?php echo $this->url(array('module' => 'ccars', 'controller' => 'index', 'action' => 'index'), 'default', true); ?>"><i class="icon-truck"></i> Courtesy Cars</a></li>
                            <li><a href="<?php echo $this->url(array('module' => 'diary', 'controller' => 'index', 'action' => 'index'), 'default', true); ?>"><i class="icon-calendar"></i> Diary</a></li>
                            <li><a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'index', 'action' => 'index'), 'default', true); ?>"><i class="icon-user"></i> Users</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="<?php echo $this->url(array('module' => 'todo', 'controller' => 'index', 'action' => 'index'))?>"><i class="icon-tasks"></i> To Do</a>
                    </li>
                </ul>
            </div>

                <div class="pull-right">
                    <ul class="nav">

                    <?php if ($this->auth()->isLoggedIn()): ?>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="icon-user"></i>
                                <?php echo $this->auth()->getUser()->name; ?>
                                <i class="icon-caret-down"></i>
                            </a>
                            <ul class="dropdown-menu">
                              <li>
                                  <a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'auth', 'action' => 'change-password'));?>">Change Password</a>
                              </li>
                            </ul>
                        </li>

                        <li><a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'auth', 'action' => 'logout'), 'default', true); ?>">Log out <i class="icon-signout"></i></a></li>
                    <?php else: ?>
                        <li><a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'auth', 'action' => 'login'), 'default', true); ?>">Log in <i class="icon-signin"></i></a></li>
                    <?php endif; ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
</div>


<div class="navbar navbar-inverse navbar-fixed-bottom hidden-phone hidden-tablet">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>

            <div class=" nav-collapse collapse">
                  <ul class="nav">
example:         panel: 132 hours        paint: 221hours        fit: 98 hours        strip: 108 hours         total hours: 559 hours
                    </ul>
            </div>
        </div>
    </div>
</div>